### ISSUE TITLE
revamps to casual mode

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/Simply-Love-SM5#41]
* rotating song banners super weird and too fast moving
* I honestly think the regular ui is pretty intuitive, we could just have a tooltip for sorting/navigating
* Agreed, the normal song wheel works fine IMO.  Keep the wheel but tweak it so that there are less selections on the screen at any one time (i.e. increase the height of each rectangle in the wheel, or something).  Keep the limited number of packs and significantly trimmed options.

**Comment by dguzek** [comment]
Input repeat speed fixed in https://github.com/dguzek/Simply-Love-SM5/commit/d833dc93cd5e25707732a6375c637e6d691ea7bd; additional small improvements in https://github.com/dguzek/Simply-Love-SM5/commit/66b982c1404d739703519bc0346566ed9280f84c.

Casual mode UI issues addressed in https://github.com/dguzek/Simply-Love-SM5/commit/8927ecef4ef5b5d77bb3acf7f9d0dc05162df623.
